dist: xenial
services:
  - postgresql
  - xvfb
addons:
  postgresql: "9.4"
  chrome: stable
  firefox: latest
before_script:
  - psql -U postgres -c "create user decide password 'decide'"
  - psql -U postgres -c "create database test_decide owner decide"
  - psql -U postgres -c "ALTER USER decide CREATEDB"
  - cp decide/local_settings.travis.py decide/local_settings.py
  - "export DISPLAY=:99.0"
  - sleep 3
language: python
python:
- '3.6'
install:
  - pip install -r requirements.txt
  - pip install codacy-coverage
  - pip install selenium
  - sudo apt-get install chromium-browser
  - sudo apt-get install -y firefox
  - wget -N https://chromedriver.storage.googleapis.com/87.0.4280.88/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip 
  - rm chromedriver_linux64.zip
  - sudo mv -f chromedriver /usr/bin
  - sudo chmod +x /usr/bin/chromedriver
  - wget "https://github.com/mozilla/geckodriver/releases/download/v0.27.0/geckodriver-v0.27.0-linux64.tar.gz"
  - tar xfz geckodriver-v0.27.0-linux64.tar.gz
  - sudo mv -f geckodriver /usr/bin
  - sudo chmod +x /usr/bin/geckodriver
jobs:
  include:
    - script:
      - cd decide
      - coverage run --branch --source=. ./manage.py test voting/tests.py:VotingTestCase.test_defensa_positive --keepdb --with-xunit
      - coverage xml
      - python-codacy-coverage -r coverage.xml
    - script:
      - cd decide
      - coverage run --branch --source=. ./manage.py test voting/tests.py:VotingTestCase.test_defensa_negative --keepdb --with-xunit
      - coverage xml
      - python-codacy-coverage -r coverage.xml

notifications:
  email:
    recipients:
      - carsantir@alum.us.es
    on_success: never 
    on_failure: always
